TD-1: Implementacion de 3 pruebas smoke
G1-ModuloV/apitest-todoist pull request #11
Opened 2024-06-29 23:52 UTC by JessieVVV

Creación de pruebas y estructura de proyectos

2024-06-29 23:57 UTC, HaroldGabrielMejiaMena commented on tests/projects/test_get_all_projects.py
Tienes que crear los asserts en otra en la carpeta asserts

2024-06-30 00:07 UTC, HaroldGabrielMejiaMena requested changes

2024-06-30 00:07 UTC, HaroldGabrielMejiaMena commented on tests/projects/test_get_all_projects.py
> +    assert response.status_code == 200, "Expected status code 200 OK"
Tienes que crear los asserts en otra en la carpeta asserts

2024-06-30 00:07 UTC, HaroldGabrielMejiaMena commented on tests/projects/test_get_all_projects.py
> +# 7)  @Automation    @Functional    @Smoke       @Validar que el Content-Type de la respuesta es application/json
Organiza mejor comentarios.

2024-06-30 04:20 UTC, JoelRojasUmss approved these changes

2024-06-30 04:43 UTC, JoelRojasUmss commented
Buen trabajo realizando los cambios solicitados.

2024-06-30 19:56 UTC, HaroldGabrielMejiaMena approved these changes

2024-06-30 19:57 UTC, merged